<a href="https://colab.research.google.com/github/RKulagowska/NumPy/blob/main/01_Numpy_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
print(np.__version__)

1.21.6


In [5]:
a= [10,20,30,40]
print(a)
type(a)

[10, 20, 30, 40]


list

In [6]:
b= np.array(a)
print(b)
type(b)

[10 20 30 40]


numpy.ndarray

In [8]:
print(b+100)

[110 120 130 140]


In [11]:
b.shape

(4,)

In [15]:
b.dtype


dtype('int64')

In [20]:
a= np.array([1,2,3,4,5,6,7,8,9,10], ndmin=2)
print(a)
a.shape

[[ 1  2  3  4  5  6  7  8  9 10]]


(1, 10)

In [24]:
a= np.array([1,2,3], dtype=complex)
print(a)
a.shape
a.dtype

[1.+0.j 2.+0.j 3.+0.j]


dtype('complex128')

In [25]:
a= np.array([[1,2,3],[4,5,6]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [26]:
a= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
a.shape

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [27]:
a= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
a.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)

In [28]:
a= np.array([[1,2,3],[4,5,6]])
a.shape =(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [37]:
a= np.array([[1,2,3],[4,5,6]])
a= a.reshape(3,2)
print(a)
print(a.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [38]:
a= np.array([1,2,3,4,5,6])
a= a.reshape(3,2)
print(a)
print(a.ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [42]:
np.empty([3,2])

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323],
       [2.5e-323, 3.0e-323]])

In [43]:
np.empty([3,2], dtype=int)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
np.zeros([3,2], dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [45]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [48]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [49]:
a= [10.2,20.3,40.3,20.3]
print(a)
type(a)
b= np.asarray(a, dtype=int)
print(b)
type(b)

[10.2, 20.3, 40.3, 20.3]
[10 20 40 20]


numpy.ndarray

In [50]:
a= (10.2,20.3,40.3,20.3)
print(a)
type(a)
b= np.asarray(a, dtype=int)
print(b)
type(b)

(10.2, 20.3, 40.3, 20.3)
[10 20 40 20]


numpy.ndarray

In [52]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [53]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [54]:
print(np.arange(5, dtype=int))

[0 1 2 3 4]


In [55]:
np.arange(5,10,2)

array([5, 7, 9])

In [57]:
np.linspace(1,11,2)

array([ 1., 11.])

In [59]:
np.linspace(1,11,4, dtype=int)

array([ 1,  4,  7, 11])

In [60]:
np.linspace(1,11,6, dtype=int)

array([ 1,  3,  5,  7,  9, 11])

In [61]:
np.linspace(1,11,6, endpoint=False)

array([1.        , 2.66666667, 4.33333333, 6.        , 7.66666667,
       9.33333333])

In [63]:
np.linspace(1,11,6, dtype=int, endpoint=False)

array([1, 2, 4, 6, 7, 9])

In [64]:
np.linspace(1,11,6, dtype=int, endpoint=False, retstep=True)

(array([1, 2, 4, 6, 7, 9]), 1.6666666666666667)