<a href="https://colab.research.google.com/github/RKulagowska/NumPy/blob/main/02_Numpy_Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
a[5]

5

In [5]:
a[:5]

array([0, 1, 2, 3, 4])

In [6]:
a[:6:2]

array([0, 2, 4])

In [7]:
a[2:4]

array([2, 3])

In [11]:
a[-1:-6:-2]

array([9, 7, 5])

In [12]:
a[-1:-6:-1]

array([9, 8, 7, 6, 5])

In [16]:
a[[0,3,4]]

array([0, 3, 4])

2 dim 

In [23]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [24]:
a[0,0]

1

In [25]:
a[1,1]

5

In [26]:
a[0,]

array([1, 2, 3])

In [28]:
a[0,1:]

array([2, 3])

In [30]:
a[1:3,1:]

array([[5, 6],
       [8, 9]])

In [32]:
a[0::2,:4:2]

array([[1, 3],
       [7, 9]])

In [43]:
a= np.array([1,2,3,4,5])
b= np.array([10,20,30,40,50])

print(a+b)

[11 22 33 44 55]


In [45]:
a= np.array([[1,2,3],[4,5,6]])
b= np.array([10,20,30])

print(a+b)

[[11 22 33]
 [14 25 36]]


In [46]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])