<a href="https://colab.research.google.com/github/RKulagowska/NumPy/blob/main/03_Numpy_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a= np.array([[1,2,3],[4,5,6]])
np.mean(a)

3.5

In [4]:
np.min(a)

1

In [6]:
np.median(a)

3.5

In [7]:
np.std(a)

1.707825127659933

In [8]:
b= np.array([10,20,30])

In [10]:
np.add(a,b)

array([[11, 22, 33],
       [14, 25, 36]])

In [12]:
np.subtract(a,b)

array([[ -9, -18, -27],
       [ -6, -15, -24]])

In [13]:
np.multiply(a,b)

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [14]:
np.power(a,3)

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [15]:
np.divide(b,a)

array([[10. , 10. , 10. ],
       [ 2.5,  4. ,  5. ]])

In [28]:
np.divide(b,10)

array([[1., 2.],
       [4., 5.]])

In [16]:
a= np.array([[1,2],[4,5]])
b= np.array([[10,20],[40,50]])

In [17]:
np.dot(a,b)  # 1*10+2*40, 1*20+2*50, 4*10+5*40, 4*20+5*50

array([[ 90, 120],
       [240, 330]])

In [19]:
np.matmul(a,b)

array([[ 90, 120],
       [240, 330]])

In [21]:
np.vdot(a,b)  # 1*10+2*20+4*40+5*50

460

In [22]:
np.inner(a,b)  # 1*10+2*20, 1*40+2*50, 4*10+5*20, 4*40+5*50

array([[ 50, 140],
       [140, 410]])

In [25]:
print(a)
np.linalg.det(a)   # 1*5 - 2*4

[[1 2]
 [4 5]]


-2.9999999999999996

In [27]:
np.random.rand(2,2)

array([[0.31986993, 0.54144859],
       [0.95523079, 0.59603498]])

In [29]:
print(a)

[[1 2]
 [4 5]]


In [31]:
np.diff(a)

array([[1],
       [1]])

In [32]:
np.cumsum(np.arange(5))

array([ 0,  1,  3,  6, 10])

In [33]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [36]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
a.size

4

In [40]:
a.dtype.name

'int64'

In [45]:
a[a<7]

array([1, 2, 4, 5])

In [46]:
x = np.append(a,b)
print(x)

[ 1  2  4  5 10 20 40 50]


In [55]:
print(a)
np.delete(a,[1])

[[1 2]
 [4 5]]


array([1, 4, 5])

In [57]:
np.insert(a,2,7)

array([1, 2, 7, 4, 5])

In [59]:
a.sum()

12

In [60]:
a.sum(axis=1)

array([3, 9])

In [61]:
a.sum(axis=0)

array([5, 7])